export const SET_IS_LOGIN = "SET_IS_LOGIN"
export const SET_IS_LOGIN_LOADING = "SET_IS_LOGIN_LOADING"
export const SET_IS_COMPANY_REGISTER_LOADING = "SET_IS_COMPANY_REGISTER_LOADING"
export const SET_IS_AUDITOR_COMPANY_REGISTER_LOADING = "SET_IS_AUDITOR_COMPANY_REGISTER_LOADING"
export const FETCH_LOGIN = "FETCH_LOGIN"
export const FETCH_COMPANY_REGISTER = "FETCH_COMPANY_REGISTER"
export const FETCH_AUDITOR_COMPANY_REGISTER = "FETCH_AUDITOR_COMPANY_REGISTER"
export const FETCH_GET_PROFILE = "FETCH_GET_PROFILE"
export const SET_PROFILE_TYPE = "SET_PROFILE_TYPE"
export const SET_COMPANY_PROFILE = "SET_COMPANY_PROFILE"
export const SET_AUDITOR_PROFILE = "SET_AUDITOR_PROFILE"
export const SET_EMPLOYER_PROFILE = "SET_EMPLOYER_PROFILE"


